# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TraceQGIS
                                 A QGIS plugin
 Permet le générer des traces a parti de fichier JSON
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-04-23
        copyright            : (C) 2025 by UGA
        email                : domingo.yoann@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TraceQGIS class from file TraceQGIS.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .trace_qgis import TraceQGIS
    return TraceQGIS(iface)
